### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ChauncyCai** [yuntaeyang/TelME#1]
Dear author, can you provide the complete data set, including video clip?

**Comment by ChauncyCai** [comment]
저에게 데이터 세트의 다운로드 링크를 보내주실 수 있나요? 제 이메일은 chuangxin7z@gmail.com입니다.

**Comment by yuntaeyang** [comment]
1. MELD : https://affective-meld.github.io/
I received the video of MELD referring to the link above.

2. In the case of IEMOCAP, it was requested to the author.
Related information is on the link: https://sail.usc.edu/iemocap/
