### ISSUE TITLE
Audio file loading error

### ISSUE THREAD

**Issue by ChauncyCai** [yuntaeyang/TelME#2]
When running python MELD/inference.py, the make_batchs() function of utils.py in the MELD folder reports an error when running. The librosa.load() function loads the mp4 file instead of the wav file. How to deal with this?

**Comment by ChauncyCai** [comment]
soundfile.LibsndfileError: Error opening 'D:/workspace/PyTorchProject/TelME/dataset/MELD.Raw/output_repeated_splits_test/dia0_utt0.mp4': Format not recognised.

**Comment by yuntaeyang** [comment]
Hello.

I don't know exactly what the problem is if it's the difference in librosa's version
There is no problem loading mp4 files with librosa.

It is recommended that you set the video folder the same as the Video_Path column in train_meld_emo.csv.

**Comment by ChauncyCai** [comment]
I checked the relevant information and found that the librosa.load() function can only read .wav

**Comment by ChauncyCai** [comment]
path = "D:\workspace\PyTorchProject\TelME\dataset\MELD.Raw\output_repeated_splits_test\dia0_utt0.mp4"
path_1 = "D:/workspace/PyTorchProject/TelME/dataset/MELD.Raw/output_repeated_splits_test/dia0_utt0.mp4"
audio, rate = librosa.load(path)


I tested it separately using the above code, and still got an error: soundfile.LibsndfileError: Error opening 'D:\\workspace\\PyTorchProject\\TelME\\dataset\\MELD.Raw\\output_repeated_splits_test\\dia0_utt0.mp4': Format not recognised.

**Comment by yuntaeyang** [comment]
<img width="1058" alt="스크린샷 2024-05-09 오후 3 08 11" src="https://github.com/yuntaeyang/TelME/assets/90027932/2600d42b-fbd1-4f60-9a63-cd6ddcf136e7">

**Comment by yuntaeyang** [comment]
You can see that the mp4 file is loaded using librosa in the Google Co Lab environment. Your problem may be the librosa version.

**Comment by ChauncyCai** [comment]
thank you very much for your help, i will try it again,

**Comment by kevinkhanhvu** [comment]
Hi @yuntaeyang I have found error when running inference.py
![image](https://github.com/yuntaeyang/TelME/assets/167272982/fc97bceb-506c-43c7-93b0-a740e3a81209)

**Comment by Greenteagodie** [comment]
Is the problem solved

**Comment by Dengdan-1999** [comment]
> I don't know exactly what the problem is if it's the difference in librosa's version There is no problem loading mp4 files with librosa.
> 
> It is recommended that you set the video folder the same as the Video_Path column in train_meld_emo.csv.

hello. have you solved this problem. would you please give me some advice? I have the same issue with you and I have tried almost all other versions of librosa like 0.7.2, 0.8.1, 0.10.0, 0.10.1, 0.10.2, 0.10.2.post1. but still post the same error! can you tell me what your setting is? my versions of the packages are as follows:
  av==10.0.0
  librosa==0.10.0
  numpy==1.23.5
  opencv-python==4.7.0.72
  pandas==1.5.3
  scikit-learn==1.2.2
  scipy==1.10.1
  torch==1.13.1
  torchaudio==0.13.1
  torchvision==0.14.1
  transformers==4.27.2
what's wrong with it? so confused!

**Comment by Vibion** [comment]
> > I don't know exactly what the problem is if it's the difference in librosa's version There is no problem loading mp4 files with librosa.
> > It is recommended that you set the video folder the same as the Video_Path column in train_meld_emo.csv.
> 
> hello. have you solved this problem. would you please give me some advice? I have the same issue with you and I have tried almost all other versions of librosa like 0.7.2, 0.8.1, 0.10.0, 0.10.1, 0.10.2, 0.10.2.post1. but still post the same error! can you tell me what your setting is? my versions of the packages are as follows: av==10.0.0 librosa==0.10.0 numpy==1.23.5 opencv-python==4.7.0.72 pandas==1.5.3 scikit-learn==1.2.2 scipy==1.10.1 torch==1.13.1 torchaudio==0.13.1 torchvision==0.14.1 transformers==4.27.2 what's wrong with it? so confused!

I can successfully load MP4 files using these versions.
av                        12.3.0                   pypi_0    pypi
librosa                   0.10.2.post1             pypi_0    pypi
